workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter pub upgrade --major-versions || true

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --debug

    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your@email.com
