name: fit_tracker
description: A comprehensive fitness tracking mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'   # match Flutter 3.22 / latest Codemagic

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Navigation
  go_router: ^16.2.1   # upgraded, stable with Flutter 3.22+

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.4.0
  glassmorphism: ^3.0.0   # ✅ already latest

  # Form Validation
  form_validator: ^2.1.1

  # Date and Time
  intl: ^0.20.2

  # Charts and Analytics
  fl_chart: ^1.11.0

  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Animations
  lottie: ^3.1.2

  # Permission Handling
  permission_handler: ^12.0.1   # ✅ stable on Android 14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # match SDK >=3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
