name: fit_tracker
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Other dependencies you might have
  provider: ^6.0.5
  go_router: ^7.2.2
  google_fonts: ^6.0.0

  # Fixed glassmorphism dependency
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
