name: fit_tracker
description: A Flutter fitness tracking app.

# Version of your app
version: 1.0.0+1

# Flutter SDK constraints
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Navigation
  go_router: ^7.2.2

  # Fonts
  google_fonts: ^6.0.0

  # Glassmorphism UI effects
  glassmorphism: ^3.0.0

  # Optional: HTTP requests (if your app uses APIs)
  http: ^1.1.1

  # Optional: JSON parsing helper
  json_annotation: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.5.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  # Optional: Add assets if your app has images
  assets:
    - assets/images/
