name: fit_tracker
description: A Flutter fitness tracking app.

# Version of your app
version: 1.0.0+1

# Flutter SDK constraints
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Navigation
  go_router: ^7.2.2

  # Fonts
  google_fonts: ^6.0.0

  # Glassmorphism UI effects
  glassmorphism: ^3.0.0

  # HTTP requests
  http: ^1.1.1

  # JSON annotation for serializable models
  json_annotation: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # JSON code generation
  build_runner: ^2.5.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  # Optional: Add assets folder if you have images
  assets:
    - assets/images/
